version: '3.8'

services:
  webapp:
    build: webapp
    restart: always
    volumes:
      - ./webapp:/app
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      FLASK_ENV: development
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASSWORD: cases123
      DATABASE_NAME: case_studies

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cases123
      MYSQL_DATABASE: case_studies
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  webapp:
  database:
